apiVersion: v1
kind: Service
metadata:
  labels:
    app: chronograf
    grp: tick
  name: chronograf
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 8888
    nodePort: 30888
    targetPort: http
  selector:
    app: chronograf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
  labels:
    app: chronograf
    grp: tick
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
        grp: tick
    spec:
      containers:
      - name: chronograf
        image: chronograf:1.7.12
        ports:
        - containerPort: 8888
          name: "http"
        env:
        - name: INFLUXDB_URL
          value: "http://influxdb:$(INFLUXDB_SERVICE_PORT)"
        # - name: BASE_PATH
        #   value: "/chronograf"
        - name: RESOURCES_PATH
          value: "/usr/share/chronograf/resources"
        - name: HTTP_AUTH-ENABLED
          value: "false"
        volumeMounts:
        - name: chronograf-data-volume
          mountPath: /var/lib/chronograf/
          subPath: chronograf/data
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "64Mi"
            cpu: "250m"
      volumes:
      - name: chronograf-data-volume
        persistentVolumeClaim:
          claimName: influxdb