apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
      - name: node-red
        image: nodered/node-red:latest
        ports:
        - containerPort: 1880
        env:
        - name: NODE_RED_USERNAME
          valueFrom:
            secretKeyRef:
              name: node-red-secret
              key: username
        - name: NODE_RED_CREDENTIAL_SECRET
          valueFrom:
            secretKeyRef:
              name: node-red-secret
              key: password
        - name: FLOWS
          value: "/data/flow.json"
        volumeMounts:
        - name: node-red-data
          mountPath: /data
        - name: flow-config
          mountPath: /data/flow.json
          subPath: flow.json
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: node-red-data
        emptyDir: {}
      - name: flow-config
        configMap:
          name: node-red-flow-config

---

apiVersion: v1
kind: Service
metadata:
  name: node-red-service
spec:
  selector:
    app: node-red
  ports:
  - protocol: TCP
    port: 1880
    targetPort: 1880
  type: LoadBalancer

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-red-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-red
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70