apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app1-hpa-network
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app1
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: container_network_transmit_bytes_total
      target:
        type: AverageValue
        averageValue: "1"  # 1 MB/s
