apiVersion: v1
kind: ConfigMap
metadata:
  name: node-red-flow-config
data:
  flow.json: |
    [
      {
        "id": "1",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
      },
      {
        "id": "2",
        "type": "inject",
        "z": "1",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": true,
        "onceDelay": 0.1,
        "x": 100,
        "y": 100,
        "wires": [
          ["3"]
        ]
      },
      {
        "id": "3",
        "type": "debug",
        "z": "1",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "false",
        "targetType": "msg",
        "x": 250,
        "y": 100,
        "wires": []
      }
    ]