apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/node-red
