apiVersion: v1
kind: Service
metadata:
  labels:
    app: pi-calculator-api
  name: pi-calculator-api
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30080
    targetPort: http
  selector:
    app: pi-calculator-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-calculator-api
  labels:
    app: pi-calculator-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: pi-calculator-api
  template:
    metadata:
      labels:
        app: pi-calculator-api
    spec:
      containers:
      - name: pi-calculator-api
        image: kurtmonge/pi-calculator-api:latest
        ports:
        - containerPort: 80
          name: "http"
        env:
        - name: InfluxDbConfig__Url
          value: "http://influxdb:$(INFLUXDB_SERVICE_PORT)"
        - name: InfluxDbConfig__UserName
          value: ""
        - name: InfluxDbConfig__Password
          value: ""
        - name: InfluxDbConfig__DatabaseInfo__DatabaseName
          value: "api_info"
        - name: InfluxDbConfig__DatabaseInfo__RetentionPolicyName
          value: "short"
        - name: InfluxDbConfig__DatabaseInfo__RetentionString
          value: "1h"
        resources:
          # requests:
          #   memory: "64Mi"
          #   cpu: "50m"
          # limits:
          #   memory: "32Mi"
          #   cpu: "100m"