apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
data:
  InfluxDbConfig__UserName: ""
  InfluxDbConfig__Password: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  InfluxDbConfig__DatabaseInfo__DatabaseName: api_info
  InfluxDbConfig__DatabaseInfo__RetentionPolicyName: short
  InfluxDbConfig__DatabaseInfo__RetentionString: 1h
  InfluxDbConfig__Url: "http://influxdb:8086"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pi-calculator-api
  name: pi-calculator-api
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30080
    targetPort: http
  selector:
    app: pi-calculator-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-calculator-api
  labels:
    app: pi-calculator-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: pi-calculator-api
  template:
    metadata:
      labels:
        app: pi-calculator-api
    spec:
      containers:
      - name: pi-calculator-api
        image: kurtmonge/pi-calculator-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: "http"
        envFrom:
          - configMapRef:
              name: influxdb-config
          - secretRef:
              name: influxdb-secrets                
        #resources:
          # requests:
          #   memory: "64Mi"
          #   cpu: "50m"
          # limits:
          #   memory: "32Mi"
          #   cpu: "100m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]'
  name: pi-calculator-api
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: pi-calculator-api
  targetCPUUtilizationPercentage: 80 # This is of the resources: requests: cpu and not the limit.
